from ._base import BaseBlocking
from .attribute_equivalence import AttributeEquivalenceBlocking
from .sorted_neighbourhood import SortedNeighborhoodBlocking
from .locality_sensitive_hashing import MinHashLSHBlocking